# Generated by Django 5.2.4 on 2025-08-01 04:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('account_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10,20}$', 'Account number must be 10-20 digits')])),
                ('branch', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[A-Z]{4}0[A-Z0-9]{6}$', 'Invalid IFSC. Format: 4 letters, 0, then 6 alphanumerics (e.g., SBIN0001234)')])),
                ('aadhaar_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Aadhaar must be a 12-digit number')])),
                ('contact_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\+91\\d{10}$', 'Mobile must be +91 followed by 10 digits')])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator('Enter a valid email address')])),
                ('card_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'Card number must be exactly 16 digits')])),
                ('card_pin', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d+$', 'PIN must be numeric only'), django.core.validators.MinLengthValidator(4, message='PIN must be at least 4 digits'), django.core.validators.MaxLengthValidator(6, message='PIN can be at most 6 digits')])),
            ],
            options={
                'db_table': 'bankuser',
            },
        ),
    ]
