# Generated by Django 5.2.4 on 2025-08-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bankuser_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATMUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='bankuser',
            old_name='contact_number',
            new_name='Contact_number',
        ),
    ]
