# Generated by Django 5.2.4 on 2025-08-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_atmuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmuser',
            name='pin_hash',
            field=models.CharField(default='pbkdf2_sha256$600000$default$xyz123hashedvalue', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atmuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
