# Generated by Django 5.2.4 on 2025-08-04 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_atmuser_pin_hash_alter_atmuser_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ATMUser',
        ),
    ]
