# Generated by Django 5.2.4 on 2025-08-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_atmuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
