# Generated by Django 5.2.4 on 2025-08-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bankuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='pin',
            field=models.CharField(default='0000', max_length=6),
        ),
    ]
