# Generated by Django 5.2.4 on 2025-08-06 04:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bankuser_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='account_number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10,12}$', 'Account number must be 12 digits')]),
        ),
    ]
